name: Workcell_3
manager_type: workcell_manager
manager_id: 01KF4PJKWGNK55NHZSB1SRA70H
description: Parallel environment 3
nodes:
  pf400: http://127.0.0.1:8000/env_3/pf400
  peeler: http://127.0.0.1:8000/env_3/peeler
  thermocycler: http://127.0.0.1:8000/env_3/thermocycler
