name: Workcell_2
manager_type: workcell_manager
manager_id: 01KF4PJM3CN8GQ342ATGQ3YQKM
description: Parallel environment 2
nodes:
  pf400: http://127.0.0.1:8000/env_2/pf400
  peeler: http://127.0.0.1:8000/env_2/peeler
  thermocycler: http://127.0.0.1:8000/env_2/thermocycler
