name: Workcell_1
manager_type: workcell_manager
manager_id: 01KF4PJMMKEZAZQ2Y42J6K0WZQ
description: Parallel environment 1
nodes:
  pf400: http://127.0.0.1:8000/env_1/pf400
  peeler: http://127.0.0.1:8000/env_1/peeler
  thermocycler: http://127.0.0.1:8000/env_1/thermocycler
