name: Workcell_0
manager_type: workcell_manager
manager_id: 01KF4PJM53QNJAWB5DXENCMD47
description: Parallel environment 0
nodes:
  pf400: http://127.0.0.1:8000/env_0/pf400
  peeler: http://127.0.0.1:8000/env_0/peeler
  thermocycler: http://127.0.0.1:8000/env_0/thermocycler
