name: Workcell_4
manager_type: workcell_manager
manager_id: 01KF4PJMQB9G6GJAYDW57T93SP
description: Parallel environment 4
nodes:
  pf400: http://127.0.0.1:8140/
  peeler: http://127.0.0.1:8141/
  thermocycler: http://127.0.0.1:8142/
