workcell_name: Workcell
manager_type: workcell_manager
workcell_id: 01JK7069DXAKAMWE0PDX6EY1PC
description: A MADSci workcell.
nodes:
  sim_ur5e_1: http://127.0.0.1:8018/
  sim_pf400_1: http://127.0.0.1:8020/
  sim_ot2_1: http://127.0.0.1:8019/
locations:
- location_name: location_1
  location_id: 01K0QB11W1RRG2ZX5K51RK83EQ
  description: The source location for the transfer
  lookup:
    sim_ur5e_1:
    - 0.0
    - -1.57
    - 0.0
    - -1.57
    - 0.0
    - 0.0
    sim_pf400_1:
    - 0.15
    - 1.57
    - 1.57
    - 0.0
    - 0.0
    - 0.2
    - 0.0
    sim_ot2_1:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  resource_definition:
    resource_name: slot_1
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: location_2
  location_id: 01K0QB11WE133NA4ESABMERH35
  description: The target location for the transfer
  lookup:
    sim_ur5e_1:
    - 0.785
    - -1.2
    - -0.5
    - -1.8
    - 0.0
    - 0.0
    sim_pf400_1:
    - 0.25
    - -1.57
    - 2.35
    - 1.57
    - 0.0
    - 0.4
    - 0.0
    sim_ot2_1:
    - 0.1
    - 0.1
    - 0.05
    - 0.05
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  resource_definition:
    resource_name: slot_2
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: platform1
  location_id: 01K2A7BZXKGA2A9ZKSW24FAN55
  description: Platform 1 for plate storage
  lookup:
    sim_pf400_1:
    - 0.09218951314687729
    - 0.16269785165786743
    - 0.7130396366119385
    - -1.0754061937332153
    - 0.36237603425979614
    - 0
    - 0
  resource_definition:
    resource_name: platform1
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: First platform location
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: platform2
  location_id: 01K2A7BZXZWEE12P76YS77JGF9
  description: Platform 2 for plate storage
  lookup:
    sim_pf400_1:
    - 0.09218951314687729
    - 0.16269785165786743
    - -0.7130396366119385
    - 1.0754061937332153
    - -0.36237603425979614
    - 0
    - 0
  resource_definition:
    resource_name: platform2
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: Second platform location
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: high_position
  location_id: 01K2A7BZY08BJGCF1Q226QGPNW
  description: High position for safe movements
  lookup:
    sim_pf400_1:
    - -0.017617395147681236
    - 0.8618930578231812
    - 0
    - 0
    - 0
    - 0
    - 0
  resource_definition:
    resource_name: high_position
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: High position for approach movements
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: approach_position
  location_id: 01K2A7BZY0BY61WM2GPXQTSQXC
  description: Approach position for safe movements
  lookup:
    sim_pf400_1:
    - -0.017617395147681236
    - 0.4626961052417755
    - 0
    - 0
    - 0
    - 0
    - 0
  resource_definition:
    resource_name: approach_position
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: Approach position for testing
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
