workcell_name: Workcell
manager_type: workcell_manager
workcell_id: 01JK7069DXAKAMWE0PDX6EY1PC
description: A MADSci workcell.
nodes:
  ot2: http://127.0.0.1:8019/
  pf400: http://127.0.0.1:8020/
  sealer: http://127.0.0.1:8021/
  peeler: http://127.0.0.1:8022/
  thermocycler: http://127.0.0.1:8023/
  hidex: http://127.0.0.1:8024/
locations:
- location_name: ot2bioalpha_deck1_wide
  location_id: 01KCWD454V0J9AHW8YWQW406GS
  description: OT-2 Deck 1 Wide
  lookup:
    pf400:
    - 0.38454803824424744
    - 0.14513998210430146
    - 0.1898307353258133
    - 1.4468275308609009
    - -3.2075114250183105
    - 0.0
    - 0
  resource_definition:
    resource_name: ot2bioalpha_deck1_wide
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: safe_path_ot2bioalpha
  location_id: 01KCWD455FH75XR9EK7AFDT397
  description: Safe path for OT-2 approach
  lookup:
    pf400:
    - 0.5400072336196899
    - 0.3368925869464874
    - 0
    - 0
    - 0
    - 0
    - 0
  resource_definition:
    resource_name: safe_path_ot2bioalpha
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: sealer_nest
  location_id: 01KCWD455FT6Z0W3SGP63BTSP9
  description: Sealer Nest
  lookup:
    pf400:
    - -0.40044429898262024
    - 0.11158271878957748
    - 0.400662362575531
    - 1.4502944946289062
    - -3.4217817783355713
    - 0
    - 0
  resource_definition:
    resource_name: sealer_nest
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: safe_path_sealer
  location_id: 01KCWD455F254686W93ATGN3ST
  description: Safe path for sealer
  lookup:
    pf400:
    - -0.40040111541748047
    - 0.4108368158340454
    - 0.4006734788417816
    - 1.4502149820327759
    - -3.4218459129333496
    - 0
    - 0
  resource_definition:
    resource_name: safe_path_sealer
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: peeler_nest
  location_id: 01KCWD455F44NFQMFPZWX55CWJ
  description: Peeler Nest
  lookup:
    pf400:
    - -0.7275359630584717
    - 0.13156265020370483
    - 0.2995404601097107
    - 1.450539469718933
    - -3.32090425491333
    - 0
    - 0
  resource_definition:
    resource_name: peeler_nest
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: safe_path_peeler
  location_id: 01KCWD455FJB37WV61HSY24979
  description: Safe path for peeler
  lookup:
    pf400:
    - -0.7274733781814575
    - 0.4308168292045593
    - 0.29955071210861206
    - 1.4504271745681763
    - -3.321009874343872
    - 0
    - 0
  resource_definition:
    resource_name: safe_path_peeler
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: bio_biometra3_nest
  location_id: 01KCWD455F3DYBMJ00MAB4BCH4
  description: Thermocycler Nest
  lookup:
    pf400:
    - -0.14252401888370514
    - 0.1632107889652252
    - -0.10332811623811722
    - -1.1150076389312744
    - 2.7891077995300293
    - 0
    - 0
  resource_definition:
    resource_name: bio_biometra3_nest
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: safe_path_biometra3
  location_id: 01KCWD455FJ88NJQRYP2MSBTKS
  description: Safe path for thermocycler
  lookup:
    pf400:
    - -0.14252401888370514
    - 0.45315250754356384
    - -0.10332823544740677
    - -1.1150076389312744
    - 2.7891077995300293
    - 0.0
    - 0
  resource_definition:
    resource_name: safe_path_biometra3
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: hidex_geraldine_high_nest
  location_id: 01KCWD455FCT6VRH91XCY38QD1
  description: Hidex Reader Nest
  lookup:
    pf400:
    - -0.7823303937911987
    - 0.07264269143342972
    - -0.7316455841064453
    - -1.0245424509048462
    - 3.327012777328491
    - 0
    - 0
  resource_definition:
    resource_name: hidex_geraldine_high_nest
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: safe_path_hidex
  location_id: 01KCWD455FN05NSTGV87TMW3P5
  description: Safe path for Hidex
  lookup:
    pf400:
    - -0.5422155261039734
    - 0.2716383635997772
    - 0
    - 0
    - 0
    - 0
    - 0
  resource_definition:
    resource_name: safe_path_hidex
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: exchange_deck_high_wide
  location_id: 01KCWD455GPRBPH8V6QTRWC64K
  description: Exchange deck wide position
  lookup:
    pf400:
    - 0.6705737709999084
    - 0.13769488036632538
    - 1.1280133724212646
    - -0.6996639370918274
    - 1.1419706344604492
    - 0
    - 0
  resource_definition:
    resource_name: exchange_deck
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: exchange_deck_high_narrow
  location_id: 01KCWD455GHP3FQHZ60H5FJRGR
  description: Exchange deck narrow position
  lookup:
    pf400:
    - 0.4321829080581665
    - 0.13769488036632538
    - 0.7130301594734192
    - -1.075421690940857
    - 0.36238372325897217
    - 0
    - 0
  resource_definition:
    resource_name: exchange_deck
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
- location_name: safe_path_exchange
  location_id: 01KCWD455GHK9WC9YEGX00A896
  description: Safe path for exchange deck
  lookup:
    pf400:
    - 0.4321829080581665
    - 0.4368929922580719
    - 0.7130301594734192
    - -1.075421690940857
    - 0.36238375306129456
    - 0
    - 0
  resource_definition:
    resource_name: safe_path_exchange
    resource_name_prefix: null
    resource_class: ''
    base_type: slot
    resource_description: null
    owner: {}
    custom_attributes: null
    capacity: 1
    default_children: null
    default_child_template: null
    default_child_quantity: null
